spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2-java11
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop:8020
    env_file:
      - ./hadoop.env
    networks:
      - services
     
  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2-java11
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://hadoop:8020
      # - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    env_file:
      - ./hadoop.env
    networks:
      - services
  hadoop : 
    image: nikammoz/hadoop:3.3.1
    build: ./hadoop
    hostaname: hadoop
    container_name: hadoop
    ports:
      - 50070:50070
      - 50075:50075
      - 8088:8088
      - 8188:8188
      - 9000:9000
    networks:
      - services

networks: 
  services:
    name: ${APP_NAME}_network
