version: '3.4'
services:
  hadoop: 
      image: nikammoz/hadoop:3.3.1
      build: .
      hostname: hadoop
      container_name: hadoop
      ports:
        - 50070:50070
        - 50075:50075
        - 8088:8088
        - 8188:8188
        - 9000:9000
        - 9870:9870
      networks:
        - services
      volumes:
        - dfs_data:/home/hduser/dfs/data
      entrypoint: /home/hduser/hadoop-${HADOOP_VERSION}/etc/hadoop/docker-entrypoint.sh

volumes:
  dfs_data:

networks: 
  services:
    name: ${APP_NAME}_network
