version: '3'

services:

  mariadb:
    image: yobasystems/alpine-mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: nikamooz
    volumes:
      - ./data/mysql:/var/lib/mysql
  