version: "2.1"
services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - kafka_zookeeper:/opt/zookeeper-3.4.13/data

  kafka1:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka1
    command: [start-kafka.sh]
    expose:
      - "8080"
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR : 1
    volumes:
      - kafka_kafka1:/opt/kafka_2.12-2.4.1/logs
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    depends_on:
      - zookeeper

  kafka2:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka2
    command: [start-kafka.sh]
    expose:
      - "8080"
    ports:
      - 9093:9092
    environment:


      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka2:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR : 1

    volumes:
      - kafka_kafka2:/opt/kafka_2.12-2.4.1/logs
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

    depends_on:
      - zookeeper


volumes:
  kafka_zookeeper:
  kafka_kafka1:
  kafka_kafka2:

