version: '3.4'
services:
  postgres:
    container_name: ${CONTAINER_NAME:-postgres}
    hostname: ${CONTAINER_NAME:-postgres}
    image: postgres:${PG_VERSION}
    volumes:
      - ./${DATA_FOLDER:-db}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS:-pgpass}
      - POSTGRES_USER=${DB_USER:-pguser}
      - POSTGRES_DB=${DB_NAME:-testdb}
    networks:
      - services
    ports:
      - ${PORT:-5432}:5432
# volumes:
#   metadata_data: {}
  # pgadmin:
  #   container_name: pgadmin4
  #   hostname: pgadmin4
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: saba123
  #   volumes:
  #     - ./pgadmin_erd:/erds
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - services  
  
networks: 
  services:
    name: ${APP_NAME}_network
